### ISSUE TITLE
Is this still usable in 2018?

### ISSUE THREAD

**Issue by wiput1999** [gregbkr/kubernetes-kargo-logging-monitoring#7]
Is this still usable in 2018?

**Comment by gregbkr** [comment]
I don't use "k8s on premise" anymore (now on gcloud), however kubespray=kargo seem still quite popular.
Alternatives will be [RKE](https://rancher.com/announcing-rke-lightweight-kubernetes-installer/) or [Kops](https://github.com/kubernetes/kops). 
Still the architecture, log/monitoring recipes and troubleshooting guide could help you start.
